
[functions.mercadolibre-auth-callback]
enabled = true
verify_jwt = true
import_map = "./functions/mercadolibre-auth-callback/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mercadolibre-auth-callback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mercadolibre-auth-callback/*.html" ]

[functions.mercadolibre-sync-listings]
enabled = true
verify_jwt = true
import_map = "./functions/mercadolibre-sync-listings/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mercadolibre-sync-listings/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mercadolibre-sync-listings/*.html" ]

[functions.mercadolibre-update-stock]
enabled = true
verify_jwt = true
import_map = "./functions/mercadolibre-update-stock/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mercadolibre-update-stock/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mercadolibre-update-stock/*.html" ]